{% set name = "libcaer" %}
{% set version = "3.3.13" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://gitlab.com/inivation/dv/{{ name }}/-/archive/{{ version }}/libcaer-{{ version }}.tar.gz
    sha256: c9ecaf75b1f2414b917e86ee5d32fd2f9c7ed0f3d6e1dcfb1d5b8ad745897389
    patches:
      - fix-build.patch

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - ninja
    - pkg-config
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - libusb
    - libopencv

test:
  commands:
    - test -f ${PREFIX}/include/libcaercpp/libcaer.hpp  # [not win]
    - if exist %PREFIX%\\Library\\include\\libcaercpp\libcaer.hpp (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/inivation/libcaer/
  license: BSD-2-Clause
  license_file: COPYING
  summary: Minimal C library to access, configure and get data from neuromorphic sensors and processors.

extra:
  recipe-maintainers:
    - Tobias-Fischer
