{% set name = "libcaer" %}
{% set version = "3.3.15" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://gitlab.com/inivation/dv/{{ name }}/-/archive/{{ version }}/libcaer-{{ version }}.tar.gz
    sha256: a0500a4810c81cb319308211fb94892fd22697579040eaf8525c6e04b9ace653
    patches:
      - fix-build.patch

build:
  number: 2
  # skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - ninja
    - pkg-config
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - libusb
    - libopencv

test:
  commands:
    - test -f ${PREFIX}/include/libcaercpp/libcaer.hpp  # [not win]
    - if exist %PREFIX%\\Library\\include\\libcaercpp\libcaer.hpp (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/inivation/libcaer/
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Minimal C library to access, configure and get data from neuromorphic sensors and processors.

extra:
  recipe-maintainers:
    - Tobias-Fischer
