{% set name = "libcaer" %}
{% set version = "3.3.12" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/inivation/{{ name }}/archive/{{ version }}.tar.gz
    sha256: 768db4aaf426db23a54a59901cc9ce178bcb0235eb846d9f0d0370cc2fc04632
    patches:
      - fix-build.patch

build:
  number: 3
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - ninja
    - pkg-config
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - libusb
    - libopencv

test:
  commands:
    - test -f ${PREFIX}/include/libcaercpp/libcaer.hpp  # [not win]
    - if exist %PREFIX%\\Library\\include\\libcaercpp\libcaer.hpp (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/inivation/libcaer/
  license: BSD-2-Clause
  license_file: COPYING
  summary: Minimal C library to access, configure and get data from neuromorphic sensors and processors.

extra:
  recipe-maintainers:
    - Tobias-Fischer
