{% set name = "libcaer" %}
{% set version = "3.3.16" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://gitlab.com/inivation/dv/{{ name }}/-/archive/{{ version }}/libcaer-{{ version }}.tar.gz
    sha256: 4ebab1ffa026d0e57629b431868f71322a0eb4c88f6f84da78c7234c9b8b80d2
    patches:
      - fix-build.patch

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cmake
    - ninja
    - pkg-config
  host:
    - libusb
    - libopencv

test:
  commands:
    - test -f ${PREFIX}/include/libcaercpp/libcaer.hpp  # [not win]
    - if exist %PREFIX%\\Library\\include\\libcaercpp\libcaer.hpp (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/inivation/libcaer/
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Minimal C library to access, configure and get data from neuromorphic sensors and processors.

extra:
  recipe-maintainers:
    - Tobias-Fischer
